version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
  web:
    environment: 
      DB_HOST: db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
     - "3000:3000"
    depends_on:
      - db
