@joe_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyNywiZXhwIjoxNjg2OTM0NzIxfQ.2gKUsA6o2-8JOA7F00C3gl6YdfLnSQITTO8i9kYrosY

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test2dv1@trest.com",
  "password": "password"
}

#Users Create (User signup)
###
POST http://localhost:3000/user.json
Content-Type: application/json 

{
  "name": "Tdersvv2",
  "email": "test2dv1@trest.com",
  "password": "password"
}

###Show Specific User
get http://localhost:3000/user/23.json


###Update User

patch http://localhost:3000/user/10.json
Content-Type: application/json
Application: Bearer {{joe_jwt}}

{
  "name": "LJohn Does",
  "profile_picture": "screenshot-2023-04-25-at-11-17-07-am.png",
  "my_new_nonprofit": 1
 
}

###Index all Users
GET http://localhost:3000/users.json


### Delete a user:

delete http://localhost:3000/user/3.json
Content-Type: application/json


### Index all Nonprofits

get http://localhost:3000/nonprofits.json



### Create new Nonprofit
post http://localhost:3000/nonprofits.json
Content-Type: application/json

{
  "name": "New Nonprofit",
  "catagory_id": 4,
  "description": "this is a new one",
  "website": "Blank.com",
  "picture": "none"
}


###Show Nonprofit

get http://localhost:3000/nonprofits/15.json



###Update Nonprofit

patch http://localhost:3000/nonprofits/2.json
Content-Type: application/json

{
    "name": "TheCeliac Fund",
    "catagory_id": 2,
    "description": "No Wheat!",
    "website": "mywebsite.com",
    "picture": "jpeg"
}

###Delete Nonprofit

Delete http://localhost:3000/nonprofits.json
Content-Type: application/json

{
  "id": 4
}

### Catagories index

get http://localhost:3000/catagories.json



