@esther_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzgyMDg3NTZ9.ttbvxxB_3Y5R0kASl39cFsI0bSvj7ca2i68qlbKogUo


#Users Create (User signup)

POST http://localhost:3000/users.json
Content-Type: application/json 

{
  "name": "Esther",
  "email": "esther@morris.com",
  "password": "password"
}

###
POST  http://localhost:3000/test.json

###

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "esther@morris.com",
  "password": "password"
}